import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { assertSleepingAccess, sleepingWrites } from '../../shared/sleepingActionCore.js';
import { prepareActionableSleepingPlan } from '../../shared/actionableSleepingPlan.js';
import { planSeriesAction, applySeriesAction } from '../../shared/multiPeriodSeriesActions.js';
import { validateLinkedSeriesCompleteness } from '../../shared/logicalSleepingSeries.js';
// Isolated fixtures only. This handler never writes to any Base44 entity.
function fixture() {
  const periods=[['p1','2099-11-01','2099-11-05'],['p2','2099-11-10','2099-11-15'],['p3','2099-11-20','2099-11-25']].map(([id,start_date,end_date])=>({id,group_id:'g',start_date,end_date,status:'ACTIVE'}));
  const tents=['80','81','82','83','84'].map(id=>({id,code:id,neighborhood_id:'n',capacity:8,tent_type:'STANDARD',working_status:'WORKING'}));
  return {group:{id:'g',stay_mode:'MULTI_PERIOD',operationally_active:true,status:'CONFIRMED'},profile:{id:'ogp'},periods,tents,neighborhoods:[{id:'n',is_vip:false}],rows:[],reservations:[],today:'2099-11-06'};
}
const prototype=(id,pax=8)=>({tent_id:id,neighborhood_id:'n',allocated_pax:pax,allocation_type:'STUDENT',gender_group:'BOYS',notes:''});
function series(ctx,id) { return ctx.periods.map(p=>({...prototype(id),id:`${id}-${p.id}`,group_id:'g',operational_group_profile_id:'ogp',stay_period_id:p.id,allocation_series_id:`s${id}`,arrival_date:p.start_date,departure_date:p.end_date,status:'CONFIRMED'})); }
function memory(ctx, failAt=0) {
  const tables={SleepingAllocation:structuredClone(ctx.rows),NeighborhoodReservation:structuredClone(ctx.reservations)};let writes=0;
  const gate=()=>{writes++;if(writes===failAt) throw new Error('fixture write failure');};
  const db=Object.fromEntries(Object.keys(tables).map(name=>[name,{
    async filter(q={},sort,limit=500,skip=0){return tables[name].filter(r=>Object.entries(q).every(([k,v])=>r[k]===v)).slice(skip,skip+limit).map(r=>({...r}));},
    async create(data){gate();const row={...data,id:crypto.randomUUID()};tables[name].push(row);return {...row};},
    async update(id,data){gate();const r=tables[name].find(r=>r.id===id);Object.assign(r,data);return {...r};},
    async delete(id){gate();tables[name]=tables[name].filter(r=>r.id!==id);}
  }]));
  return {db,tables};
}
const assert=(value,message)=>{if(!value) throw new Error(message);};
export default async function(req) {
  try {
    const base44=createClientFromRequest(req);await assertSleepingAccess(base44,await base44.auth.me());
    const results=[];
    const check=async(name,run)=>{try{await run();results.push({case:name,passed:true});}catch(error){results.push({case:name,passed:false,error:error.message});}};
    await check('A: gap remains free',()=>{const c=fixture();c.today='2099-10-31';c.rows=[{...prototype('80'),id:'other',group_id:'other',arrival_date:'2099-11-06',departure_date:'2099-11-09',status:'CONFIRMED'}];const p=prepareActionableSleepingPlan(c,[prototype('80')]);assert(p.allowed,'gap falsely blocked');assert(p.planned_rows.every(r=>!(['2099-11-06','2099-11-09'].some(d=>r.sleeping_allocation.arrival_date<=d&&d<r.sleeping_allocation.departure_date))),'gap occupied');});
    await check('B: return overlap blocks',()=>{const c=fixture();c.today='2099-10-31';c.rows=[{...prototype('80'),id:'other',group_id:'other',arrival_date:'2099-11-06',departure_date:'2099-11-11',status:'DRAFT'}];assert(!prepareActionableSleepingPlan(c,[prototype('80')]).allowed,'return not protected');});
    await check('C: partial 32 of 40 accepted',()=>{const c=fixture(),p=prepareActionableSleepingPlan(c,['80','81','82','83'].map(id=>prototype(id)));const assigned=p.planned_rows.filter(r=>r.source_stay_period_id==='p2').reduce((s,r)=>s+r.sleeping_allocation.allocated_pax,0);assert(p.allowed&&assigned===32&&40-assigned===8,'partial capacity rejected');});
    await check('D: release one series, preserve history and others',async()=>{const c=fixture();c.rows=['80','81','82'].flatMap(id=>series(c,id));const before=JSON.stringify(c.rows.filter(r=>r.allocation_series_id!=='s81'||r.departure_date<=c.today));const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_series',allocation_series_id:'s81'}));assert(before===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id!=='s81'||r.departure_date<=c.today)),'unrelated/history changed');assert(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id==='s81'&&r.departure_date>c.today).every(r=>r.status==='CANCELLED'),'future rows remain');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'released series fails validation');const next={...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation};assert(prepareActionableSleepingPlan(next,[prototype('80'),prototype('82'),prototype('83')]).allowed,'append after release blocked');});
    await check('E: pax reduction only actionable rows',async()=>{const c=fixture();c.rows=series(c,'80');const p=prepareActionableSleepingPlan(c,[prototype('80',6)]);assert(p.updates.length===2&&p.updates.every(u=>u.row.departure_date>c.today&&u.data.allocated_pax===6),'wrong pax targets');const m=memory(c),w=sleepingWrites(m.db);for(const u of p.updates)await w.update('SleepingAllocation',u.row,u.data);assert(m.tables.SleepingAllocation.find(r=>r.id==='80-p1').allocated_pax===8,'historical pax changed');assert(prepareActionableSleepingPlan({...c,rows:m.tables.SleepingAllocation},[prototype('80',6)]).updates.length===0,'pax retry not idempotent');});
    await check('F: future reassignment preserves past, validates and retries',async()=>{const c=fixture();c.rows=series(c,'80');const body={action:'reassign_series',allocation_series_id:'s80',destination_tent_id:'81',effective_period_id:'p2'};const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,body));const next={...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation};assert(JSON.stringify(next.rows.find(r=>r.id==='80-p1'))===JSON.stringify(c.rows[0]),'past changed');assert(next.rows.filter(r=>r.status!=='CANCELLED'&&r.departure_date>c.today).every(r=>r.tent_id==='81'),'future not transferred');assert(validateLinkedSeriesCompleteness(next.rows,c.periods,'g',c.today).valid,'transfer invalid');assert(planSeriesAction(next,body).already_applied,'retry creates again');assert(prepareActionableSleepingPlan(next,[prototype('81',6)]).updates.length===2,'subsequent pax edit fails');});
    await check('F2: exact self/other conflict blocks; neighborhood warns',()=>{const c=fixture();c.rows=series(c,'80');c.reservations=[{id:'nr',group_id:'other',neighborhood_id:'n',arrival_date:'2099-11-10',departure_date:'2099-11-25',status:'ACTIVE'}];const body={action:'reassign_series',allocation_series_id:'s80',destination_tent_id:'81',effective_period_id:'p2'};assert(planSeriesAction(c,body).warnings.length>0,'missing warning');c.rows.push({...series(c,'81')[1],group_id:'other'});let blocked=false;try{planSeriesAction(c,body);}catch{blocked=true;}assert(blocked,'exact conflict allowed');});
    await check('F3: mid-period move retains earlier nights',async()=>{const c=fixture();c.today='2099-11-12';c.rows=series(c,'80');const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'reassign_series',allocation_series_id:'s80',destination_tent_id:'81',effective_date:'2099-11-12'}));assert(m.tables.SleepingAllocation.find(r=>r.id==='80-p2').departure_date==='2099-11-12','earlier nights lost');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'split fails validation');});
    await check('G: release all keeps historical rows byte-for-byte',async()=>{const c=fixture();c.rows=['80','81','82'].flatMap(id=>series(c,id));const historical=JSON.stringify(c.rows.filter(r=>r.departure_date<=c.today));const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_all'}));assert(historical===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.departure_date<=c.today)),'history changed');assert(m.tables.SleepingAllocation.filter(r=>r.departure_date>c.today).every(r=>r.status==='CANCELLED'),'not all released');assert(prepareActionableSleepingPlan({...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation},[prototype('80')]).planned_rows.every(r=>r.sleeping_allocation.arrival_date>=c.today),'rebuild recreates past');});
    await check('Rollback: destination create failure retains source',async()=>{const c=fixture();c.rows=series(c,'80');const m=memory(c,2),w=sleepingWrites(m.db);let failed=false;try{await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'reassign_series',allocation_series_id:'s80',destination_tent_id:'81',effective_period_id:'p2'}));}catch{failed=true;assert((await w.rollback()).restored,'rollback incomplete');}assert(failed&&JSON.stringify(m.tables.SleepingAllocation)===JSON.stringify(c.rows),'source not restored');});
    return Response.json({success:results.every(r=>r.passed),isolated_fixtures:true,production_writes:0,results});
  } catch(error) {return Response.json({success:false,error:error.message},{status:500});}
}