import { createClientFromRequest } from 'npm:@base44/sdk@0.8.44';
import { assertSleepingAccess, sleepingWrites } from '../../shared/sleepingActionCore.js';
import { prepareActionableSleepingPlan } from '../../shared/actionableSleepingPlan.js';
import { planSeriesAction, applySeriesAction } from '../../shared/multiPeriodSeriesActions.js';
import { validateLinkedSeriesCompleteness } from '../../shared/logicalSleepingSeries.js';
import { syncSleepingNeighborhoods } from '../../shared/sleepingNeighborhoodSync.js';
// Isolated fixtures only. This handler never writes to any Base44 entity.
function fixture() {
  const periods=[['p1','2099-11-01','2099-11-05'],['p2','2099-11-10','2099-11-15'],['p3','2099-11-20','2099-11-25']].map(([id,start_date,end_date])=>({id,group_id:'g',start_date,end_date,status:'ACTIVE'}));
  const tents=['80','81','82','83','84'].map(id=>({id,code:id,neighborhood_id:'n',capacity:8,tent_type:'STANDARD',working_status:'WORKING'}));
  return {group:{id:'g',stay_mode:'MULTI_PERIOD',operationally_active:true,status:'CONFIRMED'},profile:{id:'ogp'},periods,tents,neighborhoods:[{id:'n',is_vip:false}],rows:[],reservations:[],today:'2099-11-06'};
}
const prototype=(id,pax=8)=>({tent_id:id,neighborhood_id:'n',allocated_pax:pax,allocation_type:'STUDENT',gender_group:'BOYS',notes:''});
function series(ctx,id) { return ctx.periods.map(p=>({...prototype(id),id:`${id}-${p.id}`,group_id:'g',operational_group_profile_id:'ogp',stay_period_id:p.id,allocation_series_id:`s${id}`,arrival_date:p.start_date,departure_date:p.end_date,status:'CONFIRMED'})); }
function memory(ctx, failAt=0) {
  const tables={SleepingAllocation:structuredClone(ctx.rows),NeighborhoodReservation:structuredClone(ctx.reservations)};let writes=0;
  const gate=()=>{writes++;if(writes===failAt) throw new Error('fixture write failure');};
  const db=Object.fromEntries(Object.keys(tables).map(name=>[name,{
    async filter(q={},sort,limit=500,skip=0){return tables[name].filter(r=>Object.entries(q).every(([k,v])=>r[k]===v)).slice(skip,skip+limit).map(r=>({...r}));},
    async create(data){gate();const row={...data,id:crypto.randomUUID()};tables[name].push(row);return {...row};},
    async update(id,data){gate();const r=tables[name].find(r=>r.id===id);Object.assign(r,data);return {...r};},
    async delete(id){gate();tables[name]=tables[name].filter(r=>r.id!==id);}
  }]));
  return {db,tables};
}
const assert=(value,message)=>{if(!value) throw new Error(message);};
async function applyPrepared(ctx,m,plan) {
  const writes=sleepingWrites(m.db);
  for(const item of plan.planned_rows.filter(r=>!r.existing_id)) await writes.create('SleepingAllocation',item.sleeping_allocation);
  for(const item of plan.updates) await writes.update('SleepingAllocation',item.row,item.data);
  await syncSleepingNeighborhoods(m.db,writes,ctx.group.id,plan.planned_rows.map(r=>r.sleeping_allocation),ctx.today);
}
export default async function(req) {
  try {
    const base44=createClientFromRequest(req);await assertSleepingAccess(base44,await base44.auth.me());
    const results=[];
    const check=async(name,run)=>{try{await run();results.push({case:name,passed:true});}catch(error){results.push({case:name,passed:false,error:error.message});}};
    await check('Historical completeness: ended series ignores later periods',()=>{const c=fixture();c.today='2099-11-16';c.rows=series(c,'80').slice(0,2);const before=JSON.stringify(c.rows);const validation=validateLinkedSeriesCompleteness(c.rows,c.periods,'g',c.today);assert(validation.valid,`historical series rejected: ${JSON.stringify(validation.errors)}`);assert(before===JSON.stringify(c.rows),'historical rows changed');});
    await check('Current completeness: missing future period blocks',()=>{const c=fixture();c.today='2099-11-12';c.rows=series(c,'80').slice(0,2);const validation=validateLinkedSeriesCompleteness(c.rows,c.periods,'g',c.today);assert(!validation.valid,'incomplete current series allowed');assert(validation.errors.some(error=>error.code==='MISSING_STAY_PERIOD'&&error.stay_period_id==='p3'),'missing future period not reported');});
    await check('Complete multi-period series remains valid',()=>{const c=fixture();c.today='2099-10-31';c.rows=series(c,'80');assert(validateLinkedSeriesCompleteness(c.rows,c.periods,'g',c.today).valid,'complete series rejected');});
    await check('A: gap remains free',()=>{const c=fixture();c.today='2099-10-31';c.rows=[{...prototype('80'),id:'other',group_id:'other',arrival_date:'2099-11-06',departure_date:'2099-11-09',status:'CONFIRMED'}];const p=prepareActionableSleepingPlan(c,[prototype('80')]);assert(p.allowed,'gap falsely blocked');assert(p.planned_rows.every(r=>!(['2099-11-06','2099-11-09'].some(d=>r.sleeping_allocation.arrival_date<=d&&d<r.sleeping_allocation.departure_date))),'gap occupied');});
    await check('B: return overlap blocks',()=>{const c=fixture();c.today='2099-10-31';c.rows=[{...prototype('80'),id:'other',group_id:'other',arrival_date:'2099-11-06',departure_date:'2099-11-11',status:'DRAFT'}];assert(!prepareActionableSleepingPlan(c,[prototype('80')]).allowed,'return not protected');});
    await check('C: partial 32 of 40 accepted',()=>{const c=fixture(),p=prepareActionableSleepingPlan(c,['80','81','82','83'].map(id=>prototype(id)));const assigned=p.planned_rows.filter(r=>r.source_stay_period_id==='p2').reduce((s,r)=>s+r.sleeping_allocation.allocated_pax,0);assert(p.allowed&&assigned===32&&40-assigned===8,'partial capacity rejected');});
    await check('D: release one series, preserve history and others',async()=>{const c=fixture();c.rows=['80','81','82'].flatMap(id=>series(c,id));const before=JSON.stringify(c.rows.filter(r=>r.allocation_series_id!=='s81'||r.departure_date<=c.today));const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_series',allocation_series_id:'s81'}));assert(before===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id!=='s81'||r.departure_date<=c.today)),'unrelated/history changed');assert(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id==='s81'&&r.departure_date>c.today).every(r=>r.status==='CANCELLED'),'future rows remain');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'released series fails validation');const next={...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation};assert(prepareActionableSleepingPlan(next,[prototype('80'),prototype('82'),prototype('83')]).allowed,'append after release blocked');});
    await check('E: pax reduction only actionable rows',async()=>{const c=fixture();c.rows=series(c,'80');const p=prepareActionableSleepingPlan(c,[prototype('80',6)]);assert(p.updates.length===2&&p.updates.every(u=>u.row.departure_date>c.today&&u.data.allocated_pax===6),'wrong pax targets');const m=memory(c),w=sleepingWrites(m.db);for(const u of p.updates)await w.update('SleepingAllocation',u.row,u.data);assert(m.tables.SleepingAllocation.find(r=>r.id==='80-p1').allocated_pax===8,'historical pax changed');assert(prepareActionableSleepingPlan({...c,rows:m.tables.SleepingAllocation},[prototype('80',6)]).updates.length===0,'pax retry not idempotent');});
    await check('F: future reassignment preserves past, validates and retries',async()=>{const c=fixture();c.rows=series(c,'80');const body={action:'reassign_series',allocation_series_id:'s80',destination_tent_id:'81',effective_period_id:'p2'};const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,body));const next={...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation};assert(JSON.stringify(next.rows.find(r=>r.id==='80-p1'))===JSON.stringify(c.rows[0]),'past changed');assert(next.rows.filter(r=>r.status!=='CANCELLED'&&r.departure_date>c.today).every(r=>r.tent_id==='81'),'future not transferred');assert(validateLinkedSeriesCompleteness(next.rows,c.periods,'g',c.today).valid,'transfer invalid');assert(planSeriesAction(next,body).already_applied,'retry creates again');assert(prepareActionableSleepingPlan(next,[prototype('81',6)]).updates.length===2,'subsequent pax edit fails');});
    await check('F2: exact self/other conflict blocks; neighborhood warns',()=>{const c=fixture();c.rows=series(c,'80');c.reservations=[{id:'nr',group_id:'other',neighborhood_id:'n',arrival_date:'2099-11-10',departure_date:'2099-11-25',status:'ACTIVE'}];const body={action:'reassign_series',allocation_series_id:'s80',destination_tent_id:'81',effective_period_id:'p2'};assert(planSeriesAction(c,body).warnings.length>0,'missing warning');c.rows.push({...series(c,'81')[1],group_id:'other'});let blocked=false;try{planSeriesAction(c,body);}catch{blocked=true;}assert(blocked,'exact conflict allowed');});
    await check('F3: mid-period move retains earlier nights',async()=>{const c=fixture();c.today='2099-11-12';c.rows=series(c,'80');const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'reassign_series',allocation_series_id:'s80',destination_tent_id:'81',effective_date:'2099-11-12'}));assert(m.tables.SleepingAllocation.find(r=>r.id==='80-p2').departure_date==='2099-11-12','earlier nights lost');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'split fails validation');});
    await check('G: release all keeps historical rows byte-for-byte',async()=>{const c=fixture();c.rows=['80','81','82'].flatMap(id=>series(c,id));const historical=JSON.stringify(c.rows.filter(r=>r.departure_date<=c.today));const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_all'}));assert(historical===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.departure_date<=c.today)),'history changed');assert(m.tables.SleepingAllocation.filter(r=>r.departure_date>c.today).every(r=>r.status==='CANCELLED'),'not all released');assert(prepareActionableSleepingPlan({...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation},[prototype('80')]).planned_rows.every(r=>r.sleeping_allocation.arrival_date>=c.today),'rebuild recreates past');});
    await check('H1: release one series during active period',async()=>{const c=fixture();c.today='2099-11-14';c.periods=[{id:'p-active',group_id:'g',start_date:'2099-11-10',end_date:'2099-11-18',status:'ACTIVE'}];c.rows=['80','81'].flatMap(id=>series(c,id));const untouched=JSON.stringify(c.rows.filter(r=>r.allocation_series_id==='s81'));const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_series',allocation_series_id:'s80'}));const released=m.tables.SleepingAllocation.find(r=>r.allocation_series_id==='s80');assert(released.arrival_date==='2099-11-10'&&released.departure_date===c.today&&released.status==='CONFIRMED','elapsed nights not preserved');assert(!m.tables.SleepingAllocation.some(r=>r.allocation_series_id==='s80'&&r.status!=='CANCELLED'&&r.departure_date>c.today),'future coverage remains');assert(untouched===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id==='s81')),'other series changed');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'released series fails validation');const retry=planSeriesAction({...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation},{action:'release_series',allocation_series_id:'s80'});assert(retry.already_applied&&retry.updates.length===0,'retry is not idempotent');});
    await check('H2: release all during active period',async()=>{const c=fixture();c.today='2099-11-14';c.periods=[{id:'p-active',group_id:'g',start_date:'2099-11-10',end_date:'2099-11-18',status:'ACTIVE'}];c.rows=['80','81','82'].flatMap(id=>series(c,id));const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_all'}));assert(m.tables.SleepingAllocation.every(r=>r.arrival_date==='2099-11-10'&&r.departure_date===c.today&&r.status==='CONFIRMED'),'historical segments not preserved');assert(!m.tables.SleepingAllocation.some(r=>r.status!=='CANCELLED'&&r.departure_date>c.today),'future coverage remains');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'release all fails validation');const retry=planSeriesAction({...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation},{action:'release_all'});assert(retry.already_applied&&retry.updates.length===0,'retry is not idempotent');});
    await check('I: release then re-add same tent',async()=>{const c=fixture();c.rows=series(c,'80');const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_series',allocation_series_id:'s80'}));const tombstones=JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id==='s80'));const next={...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation.filter(r=>r.status==='ACTIVE')};const plan=prepareActionableSleepingPlan(next,[{...prototype('80'),allocation_series_id:'s80'}]);await applyPrepared(next,m,plan);const newRows=m.tables.SleepingAllocation.filter(r=>r.allocation_series_id!=='s80'&&r.tent_id==='80');assert(newRows.length===2&&new Set(newRows.map(r=>r.allocation_series_id)).size===1,'new series not created');assert(tombstones===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id==='s80')),'old series revived or changed');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'re-added tent invalid');});
    await check('J: release VIP then re-add VIP',async()=>{const c=fixture();c.neighborhoods=[{id:'vip',is_vip:true}];c.tents=[{id:'80',code:'80',neighborhood_id:'vip',capacity:4,tent_type:'VIP',working_status:'WORKING'}];const vip={...prototype('80',2),neighborhood_id:'vip',allocation_type:'STAFF',gender_group:'MEN',notes:'__vip_req_0__'};c.rows=c.periods.map(p=>({...vip,id:`vip-${p.id}`,group_id:'g',operational_group_profile_id:'ogp',stay_period_id:p.id,allocation_series_id:'svip',arrival_date:p.start_date,departure_date:p.end_date,status:'CONFIRMED'}));const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_series',allocation_series_id:'svip'}));const old=JSON.stringify(m.tables.SleepingAllocation);const next={...c,rows:m.tables.SleepingAllocation,reservations:[]};const plan=prepareActionableSleepingPlan(next,[{...vip,allocation_series_id:'svip'}]);await applyPrepared(next,m,plan);assert(JSON.stringify(m.tables.SleepingAllocation.slice(0,c.rows.length))===old,'VIP tombstones changed');assert(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id!=='svip').length===2,'VIP new series missing');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'VIP re-add invalid');});
    await check('K: pax round trip 8 to 7 to 8',async()=>{const c=fixture();c.today='2099-11-14';c.periods=[{id:'p-active',group_id:'g',start_date:'2099-11-10',end_date:'2099-11-18',status:'ACTIVE'},{id:'p-future',group_id:'g',start_date:'2099-11-20',end_date:'2099-11-25',status:'ACTIVE'}];c.rows=series(c,'80');const originalHistory={...c.rows[0]};const m=memory(c);let next={...c,rows:m.tables.SleepingAllocation,reservations:[]};const down=prepareActionableSleepingPlan(next,[{...prototype('80',7),allocation_series_id:'s80'}]);await applyPrepared(next,m,down);const newSeries=m.tables.SleepingAllocation.find(r=>r.allocation_series_id!=='s80'&&r.departure_date>c.today).allocation_series_id;next={...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation.filter(r=>r.status==='ACTIVE')};const up=prepareActionableSleepingPlan(next,[{...prototype('80',8),allocation_series_id:newSeries}]);await applyPrepared(next,m,up);const retained=m.tables.SleepingAllocation.find(r=>r.id===originalHistory.id);assert(retained.arrival_date===originalHistory.arrival_date&&retained.departure_date===c.today&&retained.allocated_pax===8&&retained.status===originalHistory.status,'historical pax changed');assert(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id===newSeries&&r.departure_date>c.today).every(r=>r.allocated_pax===8),'final future pax not 8');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'round trip invalid');});
    await check('K2: pax no-op 8 to 8',()=>{const c=fixture();c.rows=series(c,'80');const plan=prepareActionableSleepingPlan(c,[{...prototype('80',8),allocation_series_id:'s80'}]);assert(plan.allowed&&plan.updates.length===0&&plan.planned_rows.every(r=>r.existing_id),'no-op planned writes');});
    await check('L: release one neighborhood',async()=>{const c=fixture();c.today='2099-11-14';c.periods=[{id:'p-active',group_id:'g',start_date:'2099-11-10',end_date:'2099-11-18',status:'ACTIVE'},{id:'p-future',group_id:'g',start_date:'2099-11-20',end_date:'2099-11-25',status:'ACTIVE'}];c.neighborhoods=[{id:'n6',is_vip:false},{id:'n7',is_vip:false}];c.tents=[{id:'60',code:'60',neighborhood_id:'n6',capacity:8,tent_type:'STANDARD',working_status:'WORKING'},{id:'70',code:'70',neighborhood_id:'n7',capacity:8,tent_type:'STANDARD',working_status:'WORKING'}];c.rows=[...series(c,'60').map(r=>({...r,neighborhood_id:'n6'})),...series(c,'70').map(r=>({...r,neighborhood_id:'n7'}))];c.reservations=c.periods.flatMap(p=>['n6','n7'].map(n=>({id:`${n}-${p.id}`,group_id:'g',operational_group_profile_id:'ogp',stay_period_id:p.id,neighborhood_id:n,arrival_date:p.start_date,departure_date:p.end_date,gender_group:'BOYS',planned_tents:1,status:'ACTIVE',source:'allocation'})));const n7Rows=JSON.stringify(c.rows.filter(r=>r.neighborhood_id==='n7')),n7Reservations=JSON.stringify(c.reservations.filter(r=>r.neighborhood_id==='n7'));const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_neighborhood',neighborhood_id:'n6'}));assert(n7Rows===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.neighborhood_id==='n7'))&&n7Reservations===JSON.stringify(m.tables.NeighborhoodReservation.filter(r=>r.neighborhood_id==='n7')),'N7 changed');const current=m.tables.SleepingAllocation.find(r=>r.id==='60-p-active');assert(current.departure_date===c.today&&current.status==='CONFIRMED','N6 history not preserved');assert(!m.tables.SleepingAllocation.some(r=>r.neighborhood_id==='n6'&&r.status!=='CANCELLED'&&r.departure_date>c.today),'N6 future remains');assert(m.tables.NeighborhoodReservation.find(r=>r.id==='n6-p-active').departure_date===c.today&&m.tables.NeighborhoodReservation.find(r=>r.id==='n6-p-future').status==='CANCELLED','N6 reservations not segmented');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'neighborhood release invalid');const retry=planSeriesAction({...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation.filter(r=>r.status==='ACTIVE')},{action:'release_neighborhood',neighborhood_id:'n6'});assert(retry.already_applied,'neighborhood retry not idempotent');});
    await check('L2: re-add released neighborhood',async()=>{const c=fixture();c.today='2099-11-14';c.periods=[{id:'p-active',group_id:'g',start_date:'2099-11-10',end_date:'2099-11-18',status:'ACTIVE'},{id:'p-future',group_id:'g',start_date:'2099-11-20',end_date:'2099-11-25',status:'ACTIVE'}];c.neighborhoods=[{id:'n6',is_vip:false},{id:'n7',is_vip:false}];c.tents=[{id:'60',code:'60',neighborhood_id:'n6',capacity:8,tent_type:'STANDARD',working_status:'WORKING'},{id:'70',code:'70',neighborhood_id:'n7',capacity:8,tent_type:'STANDARD',working_status:'WORKING'}];c.rows=[...series(c,'60').map(r=>({...r,neighborhood_id:'n6'})),...series(c,'70').map(r=>({...r,neighborhood_id:'n7'}))];const m=memory(c),w=sleepingWrites(m.db);await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'release_neighborhood',neighborhood_id:'n6'}));const oldN6=JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id==='s60')),n7=JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.neighborhood_id==='n7'));const next={...c,rows:m.tables.SleepingAllocation,reservations:m.tables.NeighborhoodReservation.filter(r=>r.status==='ACTIVE')};const plan=prepareActionableSleepingPlan(next,[{...prototype('60'),neighborhood_id:'n6',allocation_series_id:'s60'},{...prototype('70'),neighborhood_id:'n7',allocation_series_id:'s70'}]);await applyPrepared(next,m,plan);assert(oldN6===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.allocation_series_id==='s60')),'old N6 series changed');assert(n7===JSON.stringify(m.tables.SleepingAllocation.filter(r=>r.neighborhood_id==='n7')),'N7 changed on re-add');assert(m.tables.SleepingAllocation.some(r=>r.neighborhood_id==='n6'&&r.allocation_series_id!=='s60'&&r.departure_date>c.today),'new N6 series missing');assert(validateLinkedSeriesCompleteness(m.tables.SleepingAllocation,c.periods,'g',c.today).valid,'re-added neighborhood invalid');});
    await check('Rollback: destination create failure retains source',async()=>{const c=fixture();c.rows=series(c,'80');const m=memory(c,2),w=sleepingWrites(m.db);let failed=false;try{await applySeriesAction(m.db,w,c,planSeriesAction(c,{action:'reassign_series',allocation_series_id:'s80',destination_tent_id:'81',effective_period_id:'p2'}));}catch{failed=true;assert((await w.rollback()).restored,'rollback incomplete');}assert(failed&&JSON.stringify(m.tables.SleepingAllocation)===JSON.stringify(c.rows),'source not restored');});
    const body=await req.json().catch(()=>({}));
    let real_group_validation=null;
    if(body.real_group_id){
      const [realRows,realPeriods]=await Promise.all([
        base44.asServiceRole.entities.SleepingAllocation.filter({group_id:body.real_group_id}),
        base44.asServiceRole.entities.GroupStayPeriod.filter({group_id:body.real_group_id,status:'ACTIVE'},'start_date',100),
      ]);
      const before=JSON.stringify(realRows);
      const validation=validateLinkedSeriesCompleteness(realRows,realPeriods,body.real_group_id);
      real_group_validation={group_id:body.real_group_id,valid:validation.valid,errors:validation.errors,active_row_count:realRows.filter(row=>row.status!=='CANCELLED').length,historical_rows_unchanged:before===JSON.stringify(realRows)};
    }
    return Response.json({success:results.every(r=>r.passed)&&(real_group_validation?.valid??true),isolated_fixtures:true,production_writes:0,results,real_group_validation});
  } catch(error) {return Response.json({success:false,error:error.message},{status:500});}
}